services:
        nginx:
                image: nginx:1.19.8-alpine
                hostname: pech_nginx
                restart: always
                container_name: pech_nginx
                
                depends_on:
                    - app

                volumes:
                    - ./etc/pechanger.conf:/etc/nginx/conf.d/default.conf
                    - ./etc/nginx.conf:/etc/nginx/nginx.conf
                    - ./frontend/dist:/app/frontend
                ports:
                    - "80:80"
        app:
                image: pechanger:latest
                restart: always
                hostname: pech_app
                container_name: pech_app

                volumes:
                    - ./etc/pechanger_config_prod.json:/app/backend/config/pechanger_config.json

